Promise 处理异步代码相对于纯回调函数比较有序明了，但是对于同步函数写法还是挺繁琐的，下面有两种语法糖让异步更加清晰简洁

### 生成器

#### generator 函数

像指针一样下移，有点像在debug代码

```js
function* gen() {
	yield 1
	yield 2
	yield 3
}
let g = gen()
console.log(g.next())
console.log(g.next())
console.log(g.next())
console.log(g.next()) 
```

![](https://user-gold-cdn.xitu.io/2019/10/26/16e05c5073d15915?w=443&h=112&f=png&s=20314)

- 中断并完成下移`return()`
```js
function* gen() {
	yield 1
	yield 2
	yield 3
}
let g = gen()
console.log(g.next())
console.log(g.next())
console.log(g.return('完成'))
console.log(g.next()) 
```
![](https://user-gold-cdn.xitu.io/2019/10/26/16e05c8e0a184e1d?w=479&h=112&f=png&s=21553)
- 中断并抛出异常 `throw()`
```js
function* gen() {
	try {
		yield 1
		yield 2
		yield 3
	} catch(e) {
		console.log(e)
	}

}
let g = gen()
console.log(g.next())
console.log(g.next())
console.log(g.throw('异常'))
console.log(g.next()) 
```


![](https://user-gold-cdn.xitu.io/2019/10/26/16e05c943fb42af0?w=528&h=128&f=png&s=22410)
如果在异步函数里面使用 `generator` 函数怎样？

```js
function promise() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
          resolve('resolved')
    }, 1000)
  })
}

function* generate() {
 	promise().then((res) => {
    console.log(res)
  })
}

function fn() {
  const res = generate().next()
  console.log(res)
}

fn()
```


![](https://user-gold-cdn.xitu.io/2019/10/26/16e05c98d09a0b6d?w=472&h=71&f=png&s=10162)

现在发现，异步代码不需要`then`回调了，看起来和同步函数写法一样

不过现在我们有了`async`、`await`函数，将生成器进一步封装，也可以说出语法糖

### async、await函数

使用Promise 写法写一个简单的例子

```js
function promise() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
          resolve('resolved')
    }, 1000)
  })
}

function fn() {
 	promise().then((res) => {
    console.log(res)
  })
}

fn()
```


![](https://user-gold-cdn.xitu.io/2019/10/26/16e05ca6a93a9bcc?w=493&h=47&f=png&s=5346)

改写成 `async` 函数

```js
async function asyncFn() {
  console.log(await promise())
}

asyncFn()
```



![](https://user-gold-cdn.xitu.io/2019/10/26/16e05cacfd6339fe?w=994&h=47&f=png&s=9295)

**async 和 then 一样 可以达到同一个的效果，而且代码中没有回调函数的影子了**

多条异步链的情况

```js
function promise() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
          resolve(1)
    }, 1000)
  })
}

function fn() {
 	const p =  promise().then((res) => {
    	console.log('第一个then', res)
    	return res === 2 ? new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(2)
        }, 500)
   	 	}) : new Promise((resolve, reject) => {
        setTimeout(() => {
          reject(3)
        }, 500)
   	 	})
  }).then((res) => {
    console.log('第二个then', res)
  }).catch((err) => {
    console.log('异常', err)
  })
}

fn()
```

![](https://user-gold-cdn.xitu.io/2019/10/26/16e05cb37467eebb?w=504&h=70&f=png&s=8552)

使用 async 改写

```js
function promise() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
          resolve(1)
    }, 1000)
  })
}

function promise2() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
          resolve(2)
    }, 500)
  })
}

function promise3() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
          resolve(3)
    }, 500)
  })
}

async function asyncFn() {
	const step1_res = await promise()
	console.log('第一步的结果：', step1_res)
	try {
    if (step1_res === 2) {
      console.log('第二步的结果：', await promise2())
    } else {
			console.log('第二步的拒绝的结果：', await promise3())
    }
 	}
	catch(err) { 
		console.log('异常：',  err)
	}
}
asyncFn()
```

![](https://user-gold-cdn.xitu.io/2019/10/26/16e05cbb2f180de7?w=516&h=51&f=png&s=9559)

**用同步的代码写出了异步的效果**




